services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: starsim
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/starsim
      - SPRING_DATASOURCE_USERNAME=starsim
      - SPRING_DATASOURCE_PASSWORD=starsim
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=starsim
      - POSTGRES_USER=starsim
      - POSTGRES_PASSWORD=starsim